CREATE TABLE IF NOT EXISTS TestRecord (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	TestName TEXT,
	Model TEXT,
	SerialNumber TEXT,
	TestTime TEXT,
	TestEquipmentNumber TEXT,
	Operator TEXT,
	Notes TEXT,
	NoiseSamplingFrequency INTEGER,
	NoiseStatisticsTimeLength INTEGER,
	NoiseDataStr TEXT,
	ZeroValueSamplingFrequency INTEGER,
	ZeroValueStatisticsTimeLength INTEGER,
	ZeroValueDataStr TEXT,
	TemperatureSamplingFrequency INTEGER,
	TemperatureInterval INTEGER,
	MaxTemperature REAL DEFAULT 0,
	MinTemperature REAL DEFAULT 0,
	IsLimitTemperature INTEGER CHECK (IsLimitTemperature IN (0, 1)),
	TemperatureIndexStr TEXT,
	IncreaseWeightDataStr TEXT,
	SendConfigStr TEXT,
	ReceiveConfigStr TEXT,
	DiretionDataStr TEXT,
	KeepLoadingSamplingFrequency INTEGER,
	KeepLoadingStatisticsTimeLength INTEGER,
	KeepLoadingDataStr TEXT,
	CommunicateResult TEXT
);